In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
data = sns.load_dataset('titanic')

In [ ]:
data.shape

(891, 15)

In [ ]:
data.head(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

### Visualizacion de los grupos

In [ ]:
data_grouped = data.groupby('class')

data_grouped.get_group('First')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [ ]:
for key, group in data_grouped:
    print(key)
    display(group.head(3))

First

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True

Second

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True

Third

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.250,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.925,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.050,S,Third,man,True,NaN,Southampton,no,True

### Ejercicio 1

* ¿Qué porcentaje de varones y de mujeres sobrevivió dentro de cada clase (primera, segunda, tercera)?

In [ ]:
# Respuesta acá.

# Calulo el  conteo total de pasajeros por género y clase

total_pasajeros = data_grouped.size()

# Calculo el conteo pasajeros que sobrevivieron por género y clase

sobrevivientes = data_grouped['survived'].sum()

# calculo el porcentaje de pasajeros que sobrevivieron por género y clase

procentaje_sobrevivientes = (sobrevivientes / total_pasajeros) * 100

# Inprimo los porcentaje de supervivencia

display(procentaje_sobrevivientes)

class
First     62.962963
Second    47.282609
Third     24.236253
dtype: float64

### Ejercicio 2

* Crear bines para las edades: (0-18] (18-80]

* ¿Qué porcentaje de pasajeros sobrevivió, dado su sexo, franja etaria y clase?

In [ ]:
# Respuesta acá
# Creo los bines para las edades

bins = [0, 18, 80]
labels = ['0-18', '18-80']
data['age_group'] = pd.cut(data['age'], bins, labels=labels, right=True)

# Calculo el porcentaje de pasajeros que sobrevivieron según su sexo, franja etaria y clase
survived_rates = data.groupby(['sex', 'age_group', 'class'])['survived'].mean().reset_index()

# Renombro la columna para mayor claridad
survived_rates['survivedl'] = survived_rates['survived']  * 100

print(survived_rates)

       sex age_group   class  survived   survivedl
0   female      0-18   First  0.909091   90.909091
1   female      0-18  Second  1.000000  100.000000
2   female      0-18   Third  0.511628   51.162791
3   female     18-80   First  0.972973   97.297297
4   female     18-80  Second  0.900000   90.000000
5   female     18-80   Third  0.423729   42.372881
6     male      0-18   First  0.800000   80.000000
7     male      0-18  Second  0.600000   60.000000
8     male      0-18   Third  0.215686   21.568627
9     male     18-80   First  0.375000   37.500000
10    male     18-80  Second  0.071429    7.142857
11    male     18-80   Third  0.133663   13.366337

### Ejercicio 3

* Hacer una tabla pivot que la fracción de sobrevivientes y valor medio de la tarifa segun la clase y el sexo

In [ ]:
# Respuesta acá

pivot_table =data.pivot_table(index='class',columns='sex',values=['survived','fare'],aggfunc={'survived':'mean','fare':'mean'})

display(pivot_table)

              fare             survived
sex         female       male    female      male
class
First   106.125798  67.226127  0.968085  0.368852
Second   21.970121  19.741782  0.921053  0.157407
Third    16.118810  12.661633  0.500000  0.135447